module.exports = [
  {
    listingId: 10,
    userName: 'Otho',
    date: 'October 2020',
    review: 'Fugiat est ad at rerum ab. Possimus beatae suscipit sed beatae est debitis rem ex. Quibusdam neque dicta qui ut impedit et temporibus vitae. Nihil autem aliquid dolores consectetur tenetur.',
    userPicture: 'https://review-services-images-frontend-capstone.s3-us-west-1.amazonaws.com/10-0.jpg',
    cleanlinessRating: 5,
    accuracyRating: 4.2,
    locationRating: 4.3,
    valueRating: 5,
    checkInRating: 1,
    communicationRating: 2.7,
  },
  {
    listingId: 10,
    userName: 'Zena',
    date: 'May 2020',
    review: 'Iure ipsam laboriosam.',
    userPicture: 'https://review-services-images-frontend-capstone.s3-us-west-1.amazonaws.com/10-1.jpg',
    cleanlinessRating: 3.2,
    accuracyRating: 4.5,
    locationRating: 4.1,
    valueRating: 2.3,
    checkInRating: 4.5,
    communicationRating: 2,
  },
  {
    listingId: 10,
    userName: 'Coralie',
    date: 'May 2017',
    review: 'Nam sunt odit maiores earum et occaecati.',
    userPicture: 'https://review-services-images-frontend-capstone.s3-us-west-1.amazonaws.com/10-2.jpg',
    cleanlinessRating: 2.7,
    accuracyRating: 4.6,
    locationRating: 3.5,
    valueRating: 2.7,
    checkInRating: 2.1,
    communicationRating: 3.4,
  },
  {
    listingId: 10,
    userName: 'Viva',
    date: 'March 2019',
    review: 'Libero dolores vel corrupti autem.',
    userPicture: 'https://review-services-images-frontend-capstone.s3-us-west-1.amazonaws.com/10-3.jpg',
    cleanlinessRating: 4.7,
    accuracyRating: 4.7,
    locationRating: 4.3,
    valueRating: 3,
    checkInRating: 1.8,
    communicationRating: 1.9,
  },
  {
    listingId: 10,
    userName: 'Melany',
    date: 'September 2017',
    review: 'Molestiae ullam omnis ad consequatur voluptatem rerum fugiat ut.',
    userPicture: 'https://review-services-images-frontend-capstone.s3-us-west-1.amazonaws.com/10-4.jpg',
    cleanlinessRating: 4.4,
    accuracyRating: 5,
    locationRating: 2.4,
    valueRating: 4.9,
    checkInRating: 3.8,
    communicationRating: 4.2,
  },
  {
    listingId: 10,
    userName: 'Carrie',
    date: 'June 2020',
    review: 'Possimus et dolor. Voluptatum ipsum delectus libero in officia. Recusandae sed repudiandae repudiandae dolor beatae. Dolorum nesciunt voluptas iste.',
    userPicture: 'https://review-services-images-frontend-capstone.s3-us-west-1.amazonaws.com/10-5.jpg',
    cleanlinessRating: 5,
    accuracyRating: 3.1,
    locationRating: 3.4,
    valueRating: 3,
    checkInRating: 3.8,
    communicationRating: 2.3,
  },
  {
    listingId: 10,
    userName: 'Britney',
    date: 'May 2018',
    review: 'Voluptatem fuga et officia.',
    userPicture: 'https://review-services-images-frontend-capstone.s3-us-west-1.amazonaws.com/10-6.jpg',
    cleanlinessRating: 2.7,
    accuracyRating: 4.5,
    locationRating: 2.4,
    valueRating: 2.8,
    checkInRating: 2.3,
    communicationRating: 3.3,
  },
];
